include: package:lints/recommended.yaml
analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - content/build/**
linter:
  rules:
    prefer_final_locals: true
    avoid_print: false
